server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://47.93.252.91:3306/financial_database?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis-plus:
  global-config:
    db-config:
      id-type: input
  mapper-locations: classpath*:/com/example/demo/mapper/*.xml
  type-aliases-package: com.example.financialdemo.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full


application:
  doctorxiong: https://api.doctorxiong.club
